### ISSUE TITLE
Pierwsze bugi jakie zauważyłem

### ISSUE THREAD

**Issue by ReconV** [Inder00/Castlemod#2]
1. Jeżeli zabijemy przeciwnika itemki nie wylatują, przeciwnik jest teleportowany na LOBBY i dopiero w tedy itemki wylatują
2. Problemy z otwieraniem sklepu. (Czasami się da a czasami nie)
3. Brak możliwości wybierania drużyny.

Dodaj: 
Wsparcie dla ActionApi
BungeTabPlus (jakoś tak)
NameTag - Dla kolorowych nicków

Dlaczego nie dasz całego kodu xd?

**Comment by Inder00** [comment]
Na pewno wezmę pod uwagę twoje teorie, i przetestuje plugin we 3 :D dzięki za zgłoszenie
