### ISSUE TITLE
Dodanie tabliczek?

### ISSUE THREAD

**Issue by ReconV** [Inder00/Castlemod#3]
Propozycja:

Dodaj możliwość dołączenia do areny przez tabliczkę. Aby wyświetlało status (STARTUJE, W TRAKCIE, OCZEKIWANIE)

**Comment by ReconV** [comment]
Zmień renderowanie mapy na: https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/ Aby regeneracja była szybsza dal większych obiektów.

**Comment by ReconV** [comment]
Dlaczego przywracanie zamków wykonuje się dwa razy? 

`    	  MCEditSchematicFormat.getFormat(schematic).load(schematic).paste(session, new Vector(getSpawn_1_x(), getSpawn_1_y(), getSpawn_1_z()), false);
    	  //MCEditSchematicFormat.getFormat(schematic).load(schematic).paste(session, new Vector(getSpawn_1_x(), getSpawn_1_y(), getSpawn_1_z()), true);`

**Comment by Inder00** [comment]
Musiałem to przeoczyć (jak testowałem), a co do tabliczek to coś innego będzie
